### PR TITLE
add new functions

### PR DESCRIPTION
**Pull request by nightflyer88**
- support system sensors (Rx1,Rx2,RxB)
- support small and big telemetry display
- show sensor value on big telemetry window

### CODE REVIEW

**Comment by RC-Thoughts** [comment]
- Rx-values sensor-labels to list needs to come from RCT-Perc.jsn, not hardcoded with english to .lua (and .lc), app has translations to fiver languages, we need to use that everywhere in the app
- RCT-Perc.lc is not updated in the commit?
- i don't see the point on showing the sensor-value in big window?
- (What do you use to edit .lua and .jsn, indentation is of in many places?)

The sensor-selection process needs updating from my part, this is obsolete and memory-consuming way to do it.

**Comment by nightflyer88** [comment]
- ok, I still adjust the translation.
- I do not know how I compile the * .lc file?
- In order to select between the large and small window in the telemetry menu, the app must first be completely deleted and then newly added.
- I use brackets to edit

**Comment by RC-Thoughts** [comment]
- The .lc is made with Jetimodels dumper.lc.
- We should not need to put user to situation where he needs to delete the app and re-set all settings just to use big/small window. App needs to adjust the size and lcd.draw-objects automatically, re-installing app and re-doing all the settings cannot be the option. Small telemetry-window is 151x24px and big is 151x69px according to API. 

There's two way to do this, let user select the size in App-settings or in main screen settings, app can do both. Main-screen setting is preferred to preserve limited lua-allowed memory in 14/16 transmitters.

**Comment by nightflyer88** [comment]
ok, i tested with the compiled app, with this is no need to re-install the app.

**Comment by RC-Thoughts** [comment]
Added in v2.5 with other improvements. Thanks for the idea!

**Pull request closed without merging**
